/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainPakage;

import javax.swing.ImageIcon;

/**
 *
 * @author l2pc209m
 */
public class LastMes extends javax.swing.JFrame {

    /**
     * Creates new form LastMes
     */
    public LastMes() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);         
        lml2.setVisible(false);
         lml3.setVisible(false);
         ImageIcon iicon=new ImageIcon(getClass().getResource("atmIcon.png"));
         this.setIconImage(iicon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lml0 = new javax.swing.JLabel();
        lml1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lml2 = new javax.swing.JLabel();
        lml3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(513, 374));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(null);

        lml0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lml0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPakage/islamic.png"))); // NOI18N
        jPanel1.add(lml0);
        lml0.setBounds(200, 20, 100, 105);

        lml1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        lml1.setForeground(new java.awt.Color(255, 255, 255));
        lml1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lml1.setText("Do you want to do more?");
        jPanel1.add(lml1);
        lml1.setBounds(0, 167, 513, 63);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPakage/yes.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(199, 236, 57, 33);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPakage/no.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(262, 236, 57, 33);

        lml2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPakage/card out.png"))); // NOI18N
        jPanel1.add(lml2);
        lml2.setBounds(178, 11, 150, 150);

        lml3.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        lml3.setForeground(new java.awt.Color(255, 255, 255));
        lml3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lml3.setText("Good bye.....");
        jPanel1.add(lml3);
        lml3.setBounds(10, 280, 493, 52);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("x");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(478, 11, 35, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MyPage agmp=new MyPage();                  
        agmp.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        lml1.setText("Please Take your card.");
        lml2.setVisible(true);
        lml3.setVisible(true);
        lml0.setVisible(false);
        jButton1.setVisible(false);
        jButton2.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
       this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LastMes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LastMes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LastMes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LastMes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LastMes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lml0;
    private javax.swing.JLabel lml1;
    private javax.swing.JLabel lml2;
    private javax.swing.JLabel lml3;
    // End of variables declaration//GEN-END:variables
}
