/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainPakage;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.Timer;
/**
 *
 * @author aik
 */
public class LoadingWindow extends javax.swing.JFrame {
    private Timer t;
    private ActionListener a1;
    String gCardNumber;
    
    // time message
public void timemessage(String name) {
        Date dt = new Date();
        int hours = dt.getHours();
        int min = dt.getMinutes();

        if(hours>=0 && hours<=12){
             lwl1.setText("Good Morning !!!");
        }else if(hours>=12 && hours<=16){
             lwl1.setText("Good Afternoon!!!");
        }else if(hours>=16 && hours<=21){
             lwl1.setText("Good Evening !!!");
        }else if(hours>=21 && hours<=24){
             lwl1.setText("Good Night !!!");           
        }
         lwl2.setText(name);
    }   
// for sending balance to MyPage
    public void sendCardNumber(String cn){
     gCardNumber=cn;
    }
    
   
    
    
    public LoadingWindow() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null); 
         ImageIcon iicon=new ImageIcon(getClass().getResource("atmIcon.png"));
         this.setIconImage(iicon.getImage());        
    }
    
    

    LoadingWindow l = this;

    public  void  m1() {
        a1 = new ActionListener() {
            public void actionPerformed(ActionEvent ae) {
                if (jProgressBar1.getValue() < 100) {
                    jProgressBar1.setValue(jProgressBar1.getValue() + 3);
                    loadingNum.setText(""+jProgressBar1.getValue()+"%");
                    //jProgressBar1.setBackground(Color.red);
                } else {
                     MyPage mp=new MyPage();
                    mp.setVisible(true);
                      mp.receiveGCardNumber(gCardNumber);
                    l.setVisible(false);
                    t.stop();
                    System.out.println("Done!");

                }
            }
        };

        t = new Timer(100, a1);
        t.start();    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        lwl1 = new javax.swing.JLabel();
        lwl2 = new javax.swing.JLabel();
        loadingNum = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setMinimumSize(new java.awt.Dimension(589, 486));
        jPanel1.setLayout(null);
        jPanel1.add(jProgressBar1);
        jProgressBar1.setBounds(110, 300, 348, 30);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Please wait...");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 180, 200, 29);

        lwl1.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        lwl1.setForeground(new java.awt.Color(255, 255, 255));
        lwl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lwl1);
        lwl1.setBounds(10, 10, 563, 80);

        lwl2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        lwl2.setForeground(new java.awt.Color(255, 255, 255));
        lwl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lwl2);
        lwl2.setBounds(80, 90, 425, 52);

        loadingNum.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        loadingNum.setForeground(new java.awt.Color(255, 255, 255));
        loadingNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(loadingNum);
        loadingNum.setBounds(190, 220, 190, 80);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {               
               
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoadingWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    public javax.swing.JLabel loadingNum;
    private javax.swing.JLabel lwl1;
    private javax.swing.JLabel lwl2;
    // End of variables declaration//GEN-END:variables
}
