/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainPakage;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aik
 */
public class MyPage extends javax.swing.JFrame {
  Connection con; 
  PreparedStatement pstmt,pstmtT;
  ResultSet rs,rsT;
  String gCn; 
  String gPin;
  String gName;
  String gbal;
    /**
     * Creates new form MyPage
     */
    public MyPage() {
        initComponents(); 
         ImageIcon iicon=new ImageIcon(getClass().getResource("atmIcon.png"));
         this.setIconImage(iicon.getImage());        
        setResizable(false);
        setLocationRelativeTo(null); 
        mpbl1.setVisible(false);
        jButton1.setVisible(false);
        success.setVisible(false);
        mpsmb1.setVisible(false);
        jLabel14.setVisible(false);
        //tab 4 money withdraw 
        jLabel20.setVisible(false);
        mpsmb2.setVisible(false);
        monAndRec.setVisible(false);
        tablepane.setVisible(false);
        pinChM.setVisible(false);
        pinOkBtn.setVisible(false);
        pinChPic.setVisible(false);
       
    }

    public void receiveGCardNumber(String s){
      gCn=s; 
    valueFromAtmDataTable();    
    mpbl1.setText("Your Amount is "+gbal+" BDT");
    }
public void valueFromAtmDataTable(){
           try{              
               con=DriverManager.getConnection("jdbc:mysql://localhost:3306/idb","root","apcl123456");
               pstmt=con.prepareStatement("SELECT* FROM atm_data WHERE card_number ="+gCn);
               rs=pstmt.executeQuery();
               if(rs.next()){ 
                    gPin=rs.getString(2);
                    gName=rs.getString(3);                   
                    gbal=rs.getString(4);
               }else{
                    JOptionPane.showMessageDialog(null,"Can not enter into atm_data table   for gPin,gBal etc");
               }
               
           }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
           }
}    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("idb?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        transactionQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT t FROM Transaction t");
        transactionList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : transactionQuery.getResultList();
        transactionQuery1 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT t FROM Transaction t");
        transactionList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : transactionQuery1.getResultList();
        transactionQuery2 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT t FROM Transaction t");
        transactionList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : transactionQuery2.getResultList();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        mpbl1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        success = new javax.swing.JLabel();
        forA_tf = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        rtacn = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        acn = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        am = new javax.swing.JTextField();
        mpsmb1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        tablepane = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        amountPaneOfMW = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        mwam = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        labelSafe = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        mpsmb2 = new javax.swing.JButton();
        monAndRec = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        pinChPic = new javax.swing.JLabel();
        pinchpane1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        oldPin = new javax.swing.JPasswordField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        rtnpin = new javax.swing.JPasswordField();
        jButton4 = new javax.swing.JButton();
        npin = new javax.swing.JPasswordField();
        pinSPic = new javax.swing.JLabel();
        donS = new javax.swing.JLabel();
        pinChM = new javax.swing.JLabel();
        pinOkBtn = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        sl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jPanel2.setBackground(new java.awt.Color(2, 56, 39));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPakage/islamic.png"))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTabbedPane1.setBackground(new java.awt.Color(0, 102, 102));
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Select Your desire tab>>");

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Mobile banking is Coming soon...");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPakage/monese-phone-card-2-sm_171020_015023.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        jTabbedPane1.addTab("Initial Tab", jPanel3);

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.setLayout(null);

        mpbl1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        mpbl1.setForeground(new java.awt.Color(255, 255, 255));
        mpbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel5.add(mpbl1);
        mpbl1.setBounds(10, 90, 663, 46);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPakage/Stutus.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel6);
        jLabel6.setBounds(250, 90, 150, 89);

        jButton1.setBackground(new java.awt.Color(0, 51, 204));
        jButton1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPakage/okb.png"))); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);
        jButton1.setBounds(290, 160, 100, 40);

        jPanel11.setBackground(new java.awt.Color(157, 183, 221));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Call 1216 for customer care.....");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPakage/customer care.png"))); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(jLabel7)
                .addContainerGap(270, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        jPanel5.add(jPanel11);
        jPanel11.setBounds(18, 239, 665, 204);

        jTabbedPane1.addTab("Status", jPanel5);

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));
        jPanel6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(null);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPakage/MONEY  TRANSFAER.png"))); // NOI18N
        jPanel6.add(jLabel9);
        jLabel9.setBounds(200, 260, 266, 209);

        jButton2.setBackground(new java.awt.Color(51, 102, 255));
        jButton2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPakage/send.png"))); // NOI18N
        jButton2.setText("Send");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2);
        jButton2.setBounds(280, 150, 140, 38);

        success.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        success.setForeground(new java.awt.Color(255, 255, 255));
        success.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        success.setText("Successfull !!!");
        jPanel6.add(success);
        success.setBounds(180, 110, 338, 50);

        forA_tf.setBackground(new java.awt.Color(0, 102, 102));

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Retype account number :");

        rtacn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rtacnActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Account number            :");

        acn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acnActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Amount                          :");

        am.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout forA_tfLayout = new javax.swing.GroupLayout(forA_tf);
        forA_tf.setLayout(forA_tfLayout);
        forA_tfLayout.setHorizontalGroup(
            forA_tfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forA_tfLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(forA_tfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(forA_tfLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17))
                    .addGroup(forA_tfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11)))
                .addGap(18, 18, 18)
                .addGroup(forA_tfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(am, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rtacn, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acn, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        forA_tfLayout.setVerticalGroup(
            forA_tfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forA_tfLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(forA_tfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(acn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(forA_tfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(rtacn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(forA_tfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(forA_tfLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, forA_tfLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(forA_tfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(am, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        jPanel6.add(forA_tf);
        forA_tf.setBounds(50, 20, 590, 110);

        mpsmb1.setBackground(new java.awt.Color(0, 51, 204));
        mpsmb1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        mpsmb1.setForeground(new java.awt.Color(255, 255, 255));
        mpsmb1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPakage/okb.png"))); // NOI18N
        mpsmb1.setText("OK");
        mpsmb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpsmb1ActionPerformed(evt);
            }
        });
        jPanel6.add(mpsmb1);
        mpsmb1.setBounds(290, 190, 110, 40);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPakage/animatedMoney.gif"))); // NOI18N
        jPanel6.add(jLabel14);
        jLabel14.setBounds(210, 320, 230, 150);

        jTabbedPane1.addTab("Money Send", jPanel6);

        jPanel7.setBackground(new java.awt.Color(0, 102, 102));
        jPanel7.setLayout(null);

        tablepane.setBackground(new java.awt.Color(0, 102, 102));
        tablepane.setLayout(null);

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tb1);

        tablepane.add(jScrollPane2);
        jScrollPane2.setBounds(0, 20, 670, 180);

        jPanel7.add(tablepane);
        tablepane.setBounds(10, 10, 670, 200);

        amountPaneOfMW.setBackground(new java.awt.Color(157, 183, 221));
        amountPaneOfMW.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        amountPaneOfMW.setLayout(null);

        jLabel18.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Enter amount as multiplier of 500 taka");
        amountPaneOfMW.add(jLabel18);
        jLabel18.setBounds(13, 14, 634, 37);

        jLabel19.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel19.setText("Amount :");
        amountPaneOfMW.add(jLabel19);
        jLabel19.setBounds(157, 67, 96, 30);
        amountPaneOfMW.add(mwam);
        mwam.setBounds(257, 68, 245, 30);

        jButton3.setBackground(new java.awt.Color(0, 102, 102));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPakage/withdraw.png"))); // NOI18N
        jButton3.setText("Withdraw");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        amountPaneOfMW.add(jButton3);
        jButton3.setBounds(276, 116, 107, 38);

        jPanel7.add(amountPaneOfMW);
        amountPaneOfMW.setBounds(10, 20, 660, 180);

        labelSafe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPakage/badge.png"))); // NOI18N
        jPanel7.add(labelSafe);
        labelSafe.setBounds(190, 290, 310, 170);

        jLabel20.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Collect Your money and receipt....");
        jPanel7.add(jLabel20);
        jLabel20.setBounds(10, 280, 670, 40);

        mpsmb2.setBackground(new java.awt.Color(0, 51, 204));
        mpsmb2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        mpsmb2.setForeground(new java.awt.Color(255, 255, 255));
        mpsmb2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPakage/okb.png"))); // NOI18N
        mpsmb2.setText("OK");
        mpsmb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpsmb2ActionPerformed(evt);
            }
        });
        jPanel7.add(mpsmb2);
        mpsmb2.setBounds(290, 230, 110, 40);

        monAndRec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPakage/monAndRec.png"))); // NOI18N
        jPanel7.add(monAndRec);
        monAndRec.setBounds(130, 320, 430, 170);

        jTabbedPane1.addTab("Money Withdrawn", jPanel7);

        jPanel8.setBackground(new java.awt.Color(0, 102, 102));
        jPanel8.setLayout(null);

        pinChPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPakage/PinChange.png"))); // NOI18N
        jPanel8.add(pinChPic);
        pinChPic.setBounds(270, -10, 180, 240);

        pinchpane1.setBackground(new java.awt.Color(157, 183, 221));
        pinchpane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        pinchpane1.setLayout(null);

        jLabel21.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel21.setText("Old pin               :");
        pinchpane1.add(jLabel21);
        jLabel21.setBounds(130, 10, 202, 33);
        pinchpane1.add(oldPin);
        oldPin.setBounds(350, 10, 210, 30);

        jLabel22.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel22.setText("New pin             :");
        pinchpane1.add(jLabel22);
        jLabel22.setBounds(130, 50, 202, 33);

        jLabel23.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel23.setText("Retype new pin  :");
        pinchpane1.add(jLabel23);
        jLabel23.setBounds(130, 90, 202, 33);

        rtnpin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rtnpinActionPerformed(evt);
            }
        });
        pinchpane1.add(rtnpin);
        rtnpin.setBounds(350, 90, 210, 30);

        jButton4.setBackground(new java.awt.Color(0, 102, 102));
        jButton4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPakage/exchange.png"))); // NOI18N
        jButton4.setText("Change");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        pinchpane1.add(jButton4);
        jButton4.setBounds(280, 140, 120, 40);

        npin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                npinActionPerformed(evt);
            }
        });
        pinchpane1.add(npin);
        npin.setBounds(350, 50, 210, 30);

        jPanel8.add(pinchpane1);
        pinchpane1.setBounds(10, 10, 670, 190);

        pinSPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPakage/hacker-stealing-info-on-wifi.png"))); // NOI18N
        jPanel8.add(pinSPic);
        pinSPic.setBounds(80, 330, 520, 140);

        donS.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        donS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        donS.setText("Don't Share  your  pin with  other....");
        jPanel8.add(donS);
        donS.setBounds(20, 280, 670, 50);

        pinChM.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        pinChM.setForeground(new java.awt.Color(255, 255, 255));
        pinChM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pinChM.setText("Pin changing successful !!!");
        jPanel8.add(pinChM);
        pinChM.setBounds(10, 230, 680, 60);

        pinOkBtn.setBackground(new java.awt.Color(0, 51, 204));
        pinOkBtn.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        pinOkBtn.setForeground(new java.awt.Color(255, 255, 255));
        pinOkBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainPakage/okb.png"))); // NOI18N
        pinOkBtn.setText("OK");
        pinOkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinOkBtnActionPerformed(evt);
            }
        });
        jPanel8.add(pinOkBtn);
        pinOkBtn.setBounds(300, 330, 110, 40);

        jTabbedPane1.addTab("Change Pin", jPanel8);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        jPanel9.setBackground(new java.awt.Color(2, 56, 39));

        sl.setFont(new java.awt.Font("Elephant", 1, 24)); // NOI18N
        sl.setForeground(new java.awt.Color(255, 255, 255));
        sl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sl.setText("Initial Tab");
        sl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(sl, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        if(jTabbedPane1.getSelectedIndex()==0)sl.setText("Initail Tab");
        if(jTabbedPane1.getSelectedIndex()==1)sl.setText("Balance");
        if(jTabbedPane1.getSelectedIndex()==2)sl.setText("Money Transfer");
        if(jTabbedPane1.getSelectedIndex()==3)sl.setText("Money Withdrawn");
        if(jTabbedPane1.getSelectedIndex()==4)sl.setText("Change Pin");
        if(jTabbedPane1.getSelectedIndex()==5)sl.setText("Credit");
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged

    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void pinOkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinOkBtnActionPerformed
        LastMes lmw=new  LastMes();
        lmw.setVisible(true);
        this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_pinOkBtnActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // change  pin
        String s1=oldPin.getText();
        String s2=npin.getText();
        String s3=rtnpin.getText();
        String mS="[0-9]+";
        boolean i=s2.endsWith(s3);
        boolean j=s2.matches(mS);
        boolean k=s1.equals(gPin);

        if(k){
            if(i){
                if(j){
                    try{
                        pstmt=con.prepareStatement("update  atm_data set pin_number="+s2+" where card_number="+gCn);
                        int i1= pstmt.executeUpdate();
                        if(i1>0){
                            pinChM.setVisible(true);
                            pinOkBtn.setVisible(true);
                            pinchpane1.setVisible(false);
                            pinSPic.setVisible(false);
                            donS.setVisible(false);
                            pinChPic.setVisible(true);
                        }

                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null,e);
                    }
                    valueFromAtmDataTable();

                }else JOptionPane.showMessageDialog(null,"pin can be Number only");
            }else JOptionPane.showMessageDialog(null,"not matched");
        }else JOptionPane.showMessageDialog(null,"Wrong pin");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void mpsmb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpsmb2ActionPerformed
        LastMes lmw=new  LastMes();
        lmw.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mpsmb2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //  money withdraw Withdraw button
        String s1=mwam.getText();
        String mS="[0-9]+";
        boolean i=s1.matches(mS);
        if(i){
            int sInt=Integer.parseInt(s1);
            int amFGbal=Integer.parseInt(gbal);
            if(sInt%500==0){
                if(sInt<amFGbal){
                    try{

                        pstmt=con.prepareStatement("INSERT INTO transaction VALUES(?,?,?,?,?,?,?,?)");

                        java.util.Date date = new java.util.Date();
                        long t = date.getTime();
                        java.sql.Date sqlDate = new java.sql.Date(t);
                        java.sql.Time sqlTime = new java.sql.Time(t);
                        pstmt.setString(1,gCn);
                        pstmt.setString(2,gName);
                        pstmt.setString(3,""+sInt);
                        pstmt.setString(4,"Withdraw");
                        pstmt.setString(5,"N/A");
                        pstmt.setDate(6, sqlDate);
                        pstmt.setTime(7, sqlTime);
                        pstmt.setString(8, autoIn());

                        int i1= pstmt.executeUpdate();
                        if(i1>0){
                            pstmt=con.prepareStatement("update  atm_data set amount="+(amFGbal-sInt)+" where card_number="+gCn);
                            int i2= pstmt.executeUpdate();
                            if(i2>0){
                                amountPaneOfMW.setVisible(false);
                                labelSafe.setVisible(false);
                                jLabel20.setVisible(true);
                                mpsmb2.setVisible(true);
                                monAndRec.setVisible(true);
                                tablepane.setVisible(true);
                                showData();
                            }else{
                                JOptionPane.showMessageDialog(null,"Can not enter into atm_data table for insert data after Withdraw");
                            }
                        }else{
                            JOptionPane.showMessageDialog(null,"Can not enter into atm_data table for updating amount after Withdraw");
                        }
                    }catch(Exception e){
                        e.printStackTrace();
                    }
                }else JOptionPane.showMessageDialog(null,"Insufficient balance");

            }else JOptionPane.showMessageDialog(null,"Enter amount as multiplier of 500 taka");
        }else JOptionPane.showMessageDialog(null,"Amount can be Number only");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void mpsmb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpsmb1ActionPerformed
        LastMes lmw=new  LastMes();
        lmw.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_mpsmb1ActionPerformed

    private void amActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amActionPerformed

    private void acnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acnActionPerformed

    private void rtacnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rtacnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rtacnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // money send er send button
        String s1=acn.getText();
        String s2=rtacn.getText();
        String s3=am.getText();
        String mS="[0-9]+";
        boolean i=s1.equals(s2);
        boolean j=s1.matches(mS);
        boolean k=s3.matches(mS);

        if(i){
            if(j){
                if(k){
                    int amInt=Integer.parseInt(s3);
                    int amFGbal=Integer.parseInt(gbal);
                    if(amInt<amFGbal){
                        try{
                            pstmt=con.prepareStatement("INSERT INTO transaction VALUES(?,?,?,?,?,?,?,?)");

                            java.util.Date date = new java.util.Date();
                            long t = date.getTime();
                            java.sql.Date sqlDate = new java.sql.Date(t);
                            java.sql.Time sqlTime = new java.sql.Time(t);
                            pstmt.setString(1,gCn);
                            pstmt.setString(2,gName);
                            pstmt.setString(3,""+amInt);
                            pstmt.setString(4,"Money Transfer");
                            pstmt.setString(5,s1);
                            pstmt.setDate(6, sqlDate);
                            pstmt.setTime(7, sqlTime);
                            pstmt.setString(8, autoIn());

                            int i1= pstmt.executeUpdate();
                            if(i1>0){
                                pstmt=con.prepareStatement("update  atm_data set amount="+(amFGbal-amInt)+" where card_number="+gCn);
                                int i2= pstmt.executeUpdate();
                                if(i2>0){
                                    mpsmb1.setVisible(true);
                                    success.setVisible(true);
                                    jButton2.setVisible(false);
                                    forA_tf.setVisible(false);
                                    jLabel9.setVisible(false);
                                    jLabel14.setVisible(true);
                                }else{
                                    JOptionPane.showMessageDialog(null,"Can not enter into atm_data table for updating amount after sending money");
                                }
                            }
                        }catch(Exception e){
                            JOptionPane.showMessageDialog(null,e);
                        }
                    }else JOptionPane.showMessageDialog(null,"Insufficient balance");
                }else JOptionPane.showMessageDialog(null,"Amount can be Number only");
            }else JOptionPane.showMessageDialog(null,"Account no. can be Number only");
        }else JOptionPane.showMessageDialog(null,"not matched");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        LastMes lmw=new  LastMes();
        lmw.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        mpbl1.setVisible(true);
        jButton1.setVisible(true);
        jLabel6.setVisible(false);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void npinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_npinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_npinActionPerformed

    private void rtnpinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rtnpinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rtnpinActionPerformed
 
    //FOR INCREMENT
    
    public String autoIn(){
       String rk="";
         try {

            String k="Select MAX(Number) FROM transaction";
            PreparedStatement pstmt=con.prepareStatement(k);
            ResultSet rs=pstmt.executeQuery();
            String p;
            while(rs.next()){
                p=rs.getString("MAX(Number)");
                
                if(p==null){
                   p="1";
                }else{
                p=rs.getString("MAX(Number)");
                }
                
                int kp=Integer.parseInt(p);
                int kpN=kp+1;
                String kpNew=String.valueOf(kpN);
                rk=kpNew;
            }
       } catch (Exception e) {
            e.printStackTrace();
        }
        
       return rk;
    }
    //Showing data in table
    public void showData(){
	try{
         pstmt=con.prepareStatement("select* from transaction where Card_number="+gCn);
         rs=pstmt.executeQuery();
        ResultSetMetaData rsm=rs.getMetaData();
        DefaultTableModel dtm=new DefaultTableModel();
        Object[] columnnames=new Object[rsm.getColumnCount()];
          for(int i=0;i<rsm.getColumnCount(); i++){
              columnnames[i]=rsm.getColumnLabel(i+1);
                 dtm.addColumn(columnnames[i]);
            }
            
            while(rs.next()){
                Object[] data=new Object[rsm.getColumnCount()];    
               for(int i=0;i<data.length; ++i){
                   data[i]=rs.getObject(i+1);
               }
               dtm.addRow(data);
            }
            tb1.setModel(dtm);
	}catch(Exception e){
        e.printStackTrace();
        }
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField acn;
    private javax.swing.JTextField am;
    private javax.swing.JPanel amountPaneOfMW;
    private javax.swing.JLabel donS;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JPanel forA_tf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelSafe;
    private javax.swing.JLabel monAndRec;
    private javax.swing.JLabel mpbl1;
    private javax.swing.JButton mpsmb1;
    private javax.swing.JButton mpsmb2;
    private javax.swing.JTextField mwam;
    private javax.swing.JPasswordField npin;
    private javax.swing.JPasswordField oldPin;
    private javax.swing.JLabel pinChM;
    private javax.swing.JLabel pinChPic;
    private javax.swing.JButton pinOkBtn;
    private javax.swing.JLabel pinSPic;
    private javax.swing.JPanel pinchpane1;
    private javax.swing.JTextField rtacn;
    private javax.swing.JPasswordField rtnpin;
    private javax.swing.JLabel sl;
    private javax.swing.JLabel success;
    private javax.swing.JPanel tablepane;
    private javax.swing.JTable tb1;
    private java.util.List<mainPakage.Transaction> transactionList;
    private java.util.List<mainPakage.Transaction> transactionList1;
    private java.util.List<mainPakage.Transaction> transactionList2;
    private javax.persistence.Query transactionQuery;
    private javax.persistence.Query transactionQuery1;
    private javax.persistence.Query transactionQuery2;
    // End of variables declaration//GEN-END:variables
}
